export const JEOPARDY_SET_CLICKED = 'JEOPARDY_SET_CLICKED'
export const JEOPARDY_SET_DATA = 'JEOPARDY_SET_DATA'
export const JEOPARDY_SET_SELECTED = 'JEOPARDY_SET_SELECTED'
export const JEOPARDY_SET_SPREADSHEET_ID = 'JEOPARDY_SET_SPREADSHEET_ID'
